### ISSUE TITLE
Track is turnstile enabled

### ISSUE THREAD

**Issue by jac00000b** [hyperdefined/CobaltTester#42]
You can tell if turnstile is enabled on an API instance by sending a POST request to `API_URL/session`.

It will either respond with
```
{
  "status": "error",
  "error": {
    "code": "error.api.auth.not_configured"
  }
}
```
or
```
{
  "status": "error",
  "error": {
    "code": "error.api.auth.turnstile.missing"
  }
}
```

**Comment by hyperdefined** [comment]
I like this approach, as I could send a request there first before testing. If there is authentication required, don't run the rest of the test for that instance.
